version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Intalling dependencies..."
      - npm install -g yarn
      - yarn
  build:
    # build to static files
    commands:
      - yarn build
  post_build:
    # copy to aws s3
    commands:
      - aws s3 sync "build" "s3://nextjs-blog-221612"