name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install yarn
        run: npm install -g yarn serve
      - name: Build
        run: |
          yarn
          yarn build
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn serve-export
          wait-on: 'http://localhost:3000'

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: ssh proxy command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DROPLET_IP }}
        key: ${{secrets.DIGITALOCEAN_SSH_KEY}}
        username: ${{ secrets.DROPLET_USERNAME }}
        passphrase: ${{ secrets.DIGITALOCEAN_PASSPHRASE }}
        script: |
          cd repos/casey.dev
          git fetch origin main
          git reset --hard origin/main
          nvm use 18
          yarn install
          yarn build
          cp -a ./build/. /var/www/html
          service nginx restart

